[package]
name = "dynexport_prelude"
version = "0.1.0"
edition = "2021"
description = "Pre-instantiated generic exports for dynamic linking"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
